# Generated by Django 4.2.4 on 2023-08-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('Amount', models.IntegerField()),
                ('Description', models.TextField()),
                ('Data', models.DateField()),
            ],
        ),
    ]
