# Generated by Django 4.2.4 on 2023-08-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ShortDescription',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
