# Generated by Django 4.2.4 on 2023-09-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSerachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
            ],
        ),
    ]
