# Generated by Django 4.2.4 on 2023-10-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_user_cartitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='User',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
