# Generated by Django 4.2.4 on 2023-10-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.image'),
        ),
    ]
