# Generated by Django 4.2.4 on 2023-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
