# Generated by Django 4.2.4 on 2023-10-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_cartitem_item_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Products',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
