# Generated by Django 4.2.4 on 2023-10-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_cartitem_created_at_remove_cartitem_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
