# Generated by Django 4.2.4 on 2023-10-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_cartitem_item_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='User',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='products.cartitem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
