# Generated by Django 4.2.4 on 2023-09-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSerachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
            ],
        ),
    ]
