# Generated by Django 4.2.4 on 2023-09-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articleserachlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleSerachLog',
            new_name='ArticleSerach',
        ),
    ]
