# Generated by Django 4.2.4 on 2023-09-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_articleserachlog_articleserach'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleSerach',
            new_name='Search',
        ),
    ]
